### PR TITLE
Add allocate() method

### PR DESCRIPTION
**Pull request by garo**
The allocate() method allows to use an IPAddress::IPv4 or ::IPv6 object
to allocate individual host addresses so that the IPAddress object
tracks the state of which address was previously allocated.

Example:

```
  ip = IPAddress("10.0.0.0/24")
  ip.allocate  #=> "10.0.0.1/24"
  ip.allocate  #=> "10.0.0.2/24"
```

There is support for both IPv4 and IPv6 with full test coverage.

### CODE REVIEW

**Comment by garo** [comment]
Broken tests seems to be on older ruby versions about gem dependency incompatibilities.

**Comment by francisluong** [comment]
I'm fine with the feature but I'm not sure that [allocating the broadcast address for ipv4 subnets shorter than /31](https://github.com/ipaddress-gem/ipaddress/pull/84/files#diff-8738459ba4fcf3627facde75b175f754R611) makes sense.

**Comment by garo** [comment]
@francisluong I'm not entirely sure what you mean by not allocating broadcast address for shorter than /31 subnets? Would you want me to add a check which would prevent something like that and raise an error? If so please describe the case a bit better for me to fully understand what you would like me to improve.

**Comment by smortex** [comment]
:thinking: That can be tricky… As an example, on my local network 192.168.27.0/24, I have subnets that only exists for sorting out machines, e.g. 192.168.27.192/27 only has test machines… or better said, all addresses of my test machines belongs to 192.168.27.192/27… but they are configured with a /24 because I chose not to put them on a separate network: my test machines and non-test machine share the same network.

That means that while the last address of the subnet (192.168.27.223/27) is the broadcast address of 192.168.27.192/27, but since all machines have a /24 subnet configured, it is basically just a valid ip address : 192.168.27.223/24 if you prefer.

My feeling is that my setup is a corner case and has not to be handled by this code directly.  And since allocate will not return the address with all host bits set to 0, maybe it should stop before returning the address with all host bits set to 1?

```ruby
ip = @klass.new("192.168.1.0/24")
ip.allocate(253) #=> 192.168.1.254/24
ip.allocate      #=> Exception

```

**Comment by francisluong** [comment]
Fair enough.  Since the unit tests seem to spell this out pretty clearly I'm good to merge.

**Pull request merged**
