### PR TITLE
Make eql? behare like ==.

### PR DESCRIPTION
**Pull request by smortex**
Quoting `Object#eql?`

> For objects of class Object, eql? is synonymous with ==. Subclasses normally continue this tradition by aliasing eql? to their overridden == method

### CODE REVIEW

**Comment by smortex** [comment]
For the records, #22 also partially handles this by defining methods (and does more) but no news from submitter.

Either I missed that other PR when opening this one, or I wanted to follow more strictly the "tradition" by *aliasing* :wink:

**Comment by grosser** [comment]
@kaoudis can this get merged ?

**Comment by smortex** [comment]
@Adam21e I could not merge this, maybe you can?  Cc @bluemonk

**Comment by grosser** [comment]
And new please release it too, last release is from 2016 :D

**Pull request merged**
