### PR TITLE
Writing bind files with ipaddress

### PR DESCRIPTION
**Pull request by mabels**
Hello, 

i used ipaddress to write name server configuration. And there is the reverse function very handy but 
to write a complete file you need to write a SOA record which contains a shorter string than fqdn. So
i added the function to generate these special strings for ipv4 and ipv6. 

On that way a added function to ipv6 which allows the same like supernet/subnet in ipv4.

cheers

meno

### CODE REVIEW

**Comment by francisluong** [comment]
@mabels: this is out of scope for ipaddress and really deserves its own gem.  No reason you couldn't use ipaddress as a dependency.  Closing without reviewing or committing.

**Comment by mabels** [comment]
@francisluong this was opened in 2014.
I totally agree with your todays decision. I forked ipaddress around that time, and my branch is now running a:
cpp
javascript
rust
implementation with the same api. Thx for the api, but i will continue my own branch.

Please don't feel offened!

thx

meno

**Comment by francisluong** [comment]
:+1:

**Comment by mabels** [comment]
during my work to port the stuff i changed the object structure so that there is no ipv4 or ipv6 specific object. Due to this i abstracted the most of the functions to now one implementation in the ipaddress class.
Currently i did not backported that changes to ruby but if you are interessed?
I would do the backport in my branch, if you take in account to merge this back to your version 2-:)

**Pull request closed without merging**
