### PR TITLE
Travis CI fix

### PR DESCRIPTION
**Pull request by icy-arctic-fox**
This should fix the build failures and errors in Travis CI.

### CODE REVIEW

**Comment by smortex** [comment]
This PR attempted to do too much :smile:.

I dropped a couple of commits not directly related to the CI fix, and added another one to test against supported Ruby versions only.

**Comment by smortex** [comment]
@francisluong can you merge this one?

**Comment by icy-arctic-fox** [comment]
I was trying to make everything work as it was, but hey, if you're ok with dropping support for outdated versions, that fine by me. :+1: Makes things way simpler this way.

**Comment by smortex** [comment]
@icy-arctic-fox I kept your changes in a local branch: there is indeed some cleanup that is worth doing, but I would be more confident in applying them with a working test suite.

@francisluong I instructed Travis-CI to build regularly the master branch in order to know when something gets broken.

Once we have this change merged, I will attempt to rebase all pending pull-requests and hopefully, many of them will be mergeable :wink:.

**Comment by francisluong** [comment]
LGTM.  Thanks

**Pull request merged**
