### PR TITLE
Add IPv4 subnet validation

### PR DESCRIPTION
**Pull request by paudam**
Since we can create an ip with a netmask using `IPAddress.new "#{ip}/#{mask}"`, I would suggest that `IPAddress.valid? "#{ip}/#{mask}"` should also validate it.

### CODE REVIEW

**Comment by paudam** [comment]
Please excuse me, I'm not that good with IPv6 netmasking, therefore I did't implement it.

**Comment by smortex** [comment]
Hello, this is an old PR!

Now, GitHub can allows maintainers to add commits into your branch, this would allow us to add the corresponding IPv6 code.  Can you please enable this feature (on the PR page, at the bottom of the right column, under the participants list, check *Allow edits from maintainers.* )?

Thanks!

**Comment by paudam** [comment]
Hi @smortex, I have it enabled.

**Comment by smortex** [comment]
Dear @paudam, I rebased your changes on top of master and added a commit to add similar feature for IPv6.

**Pull request merged**
